/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinalcanva;

import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author joshue
 */
public class ConsultarCurso extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCurso
     */
    public ConsultarCurso() {
        initComponents();
        actualizarTabla();
    }

    private void actualizarTabla() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Seccion", "Profesor", "FechaInicio", "FechaFinal", "horaInicio", "horaFinal", "Semestre","Centro"}, ProyectoFinalCanva.cursos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Cursos e : ProyectoFinalCanva.cursos) {
            jTable1.setValueAt(e.codigo, row, 0);
            jTable1.setValueAt(e.nombre, row, 1);
            jTable1.setValueAt(e.seccion, row, 2);
            jTable1.setValueAt(e.profesor, row, 3);

            // Formatear la fecha de inicio en formato dd/MM/yyyy
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String fechaIniFormatted = dateFormat.format(e.fechaInicio);
            jTable1.setValueAt(fechaIniFormatted, row, 4);

            // Formatear la fecha de fin en formato dd/MM/yyyy
            String fechaFinFormatted = dateFormat.format(e.fechaFinal);
            jTable1.setValueAt(fechaFinFormatted, row, 5);

            jTable1.setValueAt(e.horaInicio, row, 6);
            jTable1.setValueAt(e.horaFinal, row, 7);
            jTable1.setValueAt(e.numerosem, row, 8);
            jTable1.setValueAt(e.centro, row, 9);

            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 660, 170));

        jToggleButton1.setText("Modificar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jToggleButton2.setText("Actualizar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton1.setText("Carga Masiva Json");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code her:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        ModificarCurso p = new ModificarCurso(jTable1.getSelectedRow());
        p.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            JSONParser jp = new JSONParser();
            try {
                FileReader r = new FileReader(archivo.getSelectedFile().toPath().toString());
                Object obj = jp.parse(r);

                JSONArray cursosList = (JSONArray) obj;

                for (Object c : cursosList) {
                    
                    JSONObject curso = (JSONObject) c;

                    String codigoCurso = String.valueOf(curso.get("id"));
                    String nombreCurso = (String) curso.get("nombre");
                    String seccion = (String) curso.get("seccion");
                    String fechaInicio = (String) curso.get("fecha_inicio");
                    String fechaFin = (String) curso.get("fecha_fin");
                    String horaInicio = (String) curso.get("hora_inicio");
                    String horaFin = (String) curso.get("hora_fin");
                    String profesor = (String) curso.get("profesor");
                    String centro = (String) curso.get("centro");
                    
                    Cursos nuevoCurso = new Cursos();
                    
                    nuevoCurso.nombre = nombreCurso;
                    nuevoCurso.codigo = codigoCurso;
                    nuevoCurso.seccion = seccion;
                    nuevoCurso.fechaInicio = formatter.parse(fechaInicio.substring(0,10));
                    nuevoCurso.fechaFinal = formatter.parse(fechaFin.substring(0,10));
                    nuevoCurso.profesor = profesor;
                    nuevoCurso.horaInicio =  horaInicio;
                    nuevoCurso.horaFinal = horaFin;
                    nuevoCurso.notaFinal = "0";
                    nuevoCurso.numerosem = "1";
                    nuevoCurso.centro = centro;
                    ProyectoFinalCanva.cursos.add(nuevoCurso);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
           
            actualizarTabla();
            JOptionPane.showMessageDialog(null, "Archivo Cargado Exitosamente");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
